##Deutsche Version
[[redirects]]
  from = "/"
  to = "WebseiteDeutsch/index.html"
  status = 301
  force = true
  conditions = {Country = ["DE"]}
[[redirects]]
  from = "/fotos.html"
  to = "WebseiteDeutsch/De_fotos.html"
  status = 301
  force = true

[[redirects]]
  from = "/Satzung.html"
  to = "WebseiteDeutsch/De_Satzung.html"
  status = 301
  force = true

[[redirects]]
  from = "/kontakt.html"
  to = "WebseiteDeutsch/De_kontakt.html"
  status = 301
  force = true

## From german to arabic 
[[redirects]]
  from = "/GeToAr"
  to = "WebseiteArabisch/Ar_index.html"
  status = 301
  force = true

##Arabische Version
[[redirects]]
  from = "/ar_Satzung.html"
  to = "WebseiteArabisch/Ar_Satzung.html"
  status = 301
  force = true

[[redirects]]
  from = "/ar_kontakt.html"
  to = "WebseiteArabisch/Ar_kontakt.html"
  status = 301
  force = true
[[redirects]]
  from = "/ar_fotos.html"
  to = "WebseiteArabisch/Ar_fotos.html"
  status = 301
  force = true

  [[redirects]]
  from = "/"
  to = "WebseiteArabisch/Ar_index.html"
  status = 301
  force = true
  conditions = {Country = ["MA"]}
